name: lint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

jobs:
  lint:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Login to GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npm run typecheck
      - name: Lint with ESLint
        run: npm run lint
      - name: Check formatting with Prettier
        run: npx prettier src --check
