name: publish

on: [workflow_dispatch]

env:
  MAIN_REPO: ncsa/geo-explorer
  NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

jobs:
  # ----------------------------------------------------------------------
  # NODE BUILD
  # ----------------------------------------------------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout source code
      - uses: actions/checkout@v4

      # setup node
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      # generate npmrc file to login to github package registry
      - name: Login to GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc

      # Install dependencies
      - name: build
        run: npm ci

      # build NPM package
      - name: build
        run: npm run build

      # Semantic release
      - name: release
        run: npx semantic-release
